# Copyright (C) 2022 The ORT Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# License-Filename: LICENSE

name: 'ORT for GitHub Action'
description: 'A GitHub Action to run ORT'
author: 'The ORT Project Authors'

inputs:
  image:
    description: 'URL for ORT Docker image to use.'
    required: false
    default: 'ghcr.io/alliander-opensource/ort-container:latest'
  sw-name:
    description: |
      Name of project, product or component to be scanned.
      By default the name of the repository is used as shown in its clone URL.
    required: false
  sw-version:
    description: |
      Project version number or release name (use the version from package metadata, not VCS revision).
      By default, the Git short SHA is used.
    required: false
  project-dir:
    description: |
      Path to directory containing project to be analyzed/scanned with ORT.
    required: false
    default: 'project'
  allow-dynamic-versions:
    description: |
      Set to 'true' only if dynamic dependency versions are allowed (note version ranges specified for dependencies may cause unstable results).
      This field applies only to package managers that support lock files, e.g. NPM.
    required: false
    default: true
  create-source-code-bundle:
    description: |
      Set to 'true' only if an archive of source code for configured packages is to be created.
    required: false
    default: false
  log-level:
    description: |
      Set value to 'debug' to see additional debug output to help tracking down errors.
    required: false
    default: 'warn'
  reporters:
    description: |
      List of ORT reporters to run.
    required: false
    default: CycloneDx,SpdxDocument,WebApp

runs:
  using: 'composite'
  steps:
      run: echo Run ORT on project ${{ inputs.sw-name }}.
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
